# Change these first
owner: Jst-Tan # Your GitHub organization or username, where this repository lives
repo: WWW-Uptime-Tracker # The name of this repository

sites:
  - name: Google
    url: https://www.google.com
  - name: Wikipedia
    url: https://en.wikipedia.org
  - name: Bluesky App
    url: https://bsky.app/
  - name: Facebook 
    url: https://facebook.com 
  - name: PayPal 
    url: https://www.paypal.com
  - name: Reddit
    url: https://www.reddit.com/
  - name: Huzzler.so 
    url: https://huzzler.so/
  - name: Twitter (X)
    url: https://x.com/
  - name: GitHub 
    url: https://github.com 
  - name: Roblox 
    url: https://roblox.com 
  - name: CoinMarketCap
    url: https://coinmarketcap.com/

status-website:
  # Add your custom domain name, or remove the `cname` line if you don't have a domain
  # Uncomment the `baseUrl` line if you don't have a custom domain and add your repo name there
  baseUrl: /WWW-Uptimu-Tracker
  logoUrl: https://raw.githubusercontent.com/upptime/upptime.js.org/master/static/img/icon.svg
  name: Upptime
  introTitle: "**Upptime** is the open-source uptime monitor and status page, powered entirely by GitHub."
  introMessage: This is a sample status page which uses **real-time** data from our [GitHub repository](https://github.com/upptime/upptime). No server required — just GitHub Actions, Issues, and Pages. [**Get your own for free**](https://github.com/upptime/upptime)
  navbar:
    - title: Status
      href: /
    - title: GitHub
      href: https://github.com/$OWNER/$REPO

# Upptime also supports notifications, assigning issues, and more
# See https://upptime.js.org/docs/configuration
